// Code generated by Imbue's build process. DO NOT EDIT.

package imbue

import "context"

// Invoke1 calls a function with a single dependency.
func (con *Container) Invoke1[D any](
	ctx context.Context,
	fn func(context.Context, D) error,
	options ...InvokeOption,
) error {
	v1, err := get[D](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1))
}

// Invoke2 calls a function with 2 dependencies.
func (con *Container) Invoke2[D1, D2 any](
	ctx context.Context,
	fn func(context.Context, D1, D2) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2))
}

// Invoke3 calls a function with 3 dependencies.
func (con *Container) Invoke3[D1, D2, D3 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3))
}

// Invoke4 calls a function with 4 dependencies.
func (con *Container) Invoke4[D1, D2, D3, D4 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3, D4) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v4, err := get[D4](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3, v4))
}

// Invoke5 calls a function with 5 dependencies.
func (con *Container) Invoke5[D1, D2, D3, D4, D5 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3, D4, D5) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v4, err := get[D4](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v5, err := get[D5](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3, v4, v5))
}

// Invoke6 calls a function with 6 dependencies.
func (con *Container) Invoke6[D1, D2, D3, D4, D5, D6 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3, D4, D5, D6) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v4, err := get[D4](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v5, err := get[D5](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v6, err := get[D6](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3, v4, v5, v6))
}

// Invoke7 calls a function with 7 dependencies.
func (con *Container) Invoke7[D1, D2, D3, D4, D5, D6, D7 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3, D4, D5, D6, D7) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v4, err := get[D4](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v5, err := get[D5](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v6, err := get[D6](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v7, err := get[D7](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3, v4, v5, v6, v7))
}

// Invoke8 calls a function with 8 dependencies.
func (con *Container) Invoke8[D1, D2, D3, D4, D5, D6, D7, D8 any](
	ctx context.Context,
	fn func(context.Context, D1, D2, D3, D4, D5, D6, D7, D8) error,
	options ...InvokeOption,
) error {
	v1, err := get[D1](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v2, err := get[D2](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v3, err := get[D3](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v4, err := get[D4](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v5, err := get[D5](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v6, err := get[D6](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v7, err := get[D7](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	v8, err := get[D8](con).Resolve(ctx)
	if err != nil {
		return filterInvokeError(err)
	}

	return filterInvokeError(fn(ctx, v1, v2, v3, v4, v5, v6, v7, v8))
}

// Invoke1 calls a function with a single dependency.
//
// Deprecated: Use [Container.Invoke1] instead.
//
//go:fix inline
func Invoke1[D any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D) error,
	options ...InvokeOption,
) error {
	return con.Invoke1(ctx, fn, options...)
}

// Invoke2 calls a function with 2 dependencies.
//
// Deprecated: Use [Container.Invoke2] instead.
//
//go:fix inline
func Invoke2[D1, D2 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2) error,
	options ...InvokeOption,
) error {
	return con.Invoke2(ctx, fn, options...)
}

// Invoke3 calls a function with 3 dependencies.
//
// Deprecated: Use [Container.Invoke3] instead.
//
//go:fix inline
func Invoke3[D1, D2, D3 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3) error,
	options ...InvokeOption,
) error {
	return con.Invoke3(ctx, fn, options...)
}

// Invoke4 calls a function with 4 dependencies.
//
// Deprecated: Use [Container.Invoke4] instead.
//
//go:fix inline
func Invoke4[D1, D2, D3, D4 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3, D4) error,
	options ...InvokeOption,
) error {
	return con.Invoke4(ctx, fn, options...)
}

// Invoke5 calls a function with 5 dependencies.
//
// Deprecated: Use [Container.Invoke5] instead.
//
//go:fix inline
func Invoke5[D1, D2, D3, D4, D5 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3, D4, D5) error,
	options ...InvokeOption,
) error {
	return con.Invoke5(ctx, fn, options...)
}

// Invoke6 calls a function with 6 dependencies.
//
// Deprecated: Use [Container.Invoke6] instead.
//
//go:fix inline
func Invoke6[D1, D2, D3, D4, D5, D6 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3, D4, D5, D6) error,
	options ...InvokeOption,
) error {
	return con.Invoke6(ctx, fn, options...)
}

// Invoke7 calls a function with 7 dependencies.
//
// Deprecated: Use [Container.Invoke7] instead.
//
//go:fix inline
func Invoke7[D1, D2, D3, D4, D5, D6, D7 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3, D4, D5, D6, D7) error,
	options ...InvokeOption,
) error {
	return con.Invoke7(ctx, fn, options...)
}

// Invoke8 calls a function with 8 dependencies.
//
// Deprecated: Use [Container.Invoke8] instead.
//
//go:fix inline
func Invoke8[D1, D2, D3, D4, D5, D6, D7, D8 any](
	ctx context.Context,
	con *Container,
	fn func(context.Context, D1, D2, D3, D4, D5, D6, D7, D8) error,
	options ...InvokeOption,
) error {
	return con.Invoke8(ctx, fn, options...)
}
